In [58]:
import pandas as pd
import numpy as np
import sqlalchemy
from sqlalchemy import create_engine
import json

In [170]:
# read JSON file
jsonFile = "Resources/rating.json"
# load json in variable
data = json.loads(open(jsonFile,"r").read()) 
data['dog_breeds']
# convert dog ratings to dataframe
dfDogRatings = pd.DataFrame.from_dict(data['dog_breeds'], orient='index')
dfDogRatings.head(5)

,Adaptability,All Around Friendliness,Exercise Needs,Health Grooming,Trainability,Adapts Well to Apartment Living,Affectionate with Family,Amount Of Shedding,Dog Friendly,Drooling Potential,...,Potential For Playfulness,Potential For Weight Gain,Prey Drive,Sensitivity Level,Size,Tendency To Bark Or Howl,Tolerates Being Alone,Tolerates Cold Weather,Tolerates Hot Weather,Wanderlust Potential
Affenpinscher,3,3,4,2,3,5,5,1,4,1,...,4,3,3,3,1,2,1,3,3,2
Afghan Hound,4,4,4,2,3,5,5,4,4,1,...,4,1,5,5,4,2,2,5,5,5
Airedale Terrier,2,4,5,3,5,1,4,2,4,1,...,5,4,5,3,3,4,2,3,3,4
Akita,3,2,4,4,4,2,5,5,1,5,...,5,4,4,5,4,5,1,5,2,4
Alaskan Klee Kai,3,3,4,3,4,3,4,4,2,2,...,4,2,5,4,2,3,2,5,2,4

In [171]:
# reset index
dfDogRatings.reset_index(inplace=True)
# duplicate dataframe with only necessary ciolumns
dfDogRatingsClean = dfDogRatings[['index',' All Around Friendliness',' Trainability','Amount Of Shedding', 'Exercise Needs', 'General Health']].copy()
# clean up column names
dfDogRatingsClean=dfDogRatingsClean.rename(columns={'index':'Breed',' All Around Friendliness':'All Around Friendliness',' Trainability':'Trainability',})

In [61]:
# connect to server
engine = sqlalchemy.create_engine('mysql+pymysql://root:olivia@127.0.0.1:3306') 
# create db
engine.execute("CREATE DATABASE ultimutt")
# select new db
engine.execute("USE ultimutt")

In [136]:
# create 'ratings' table
engine.execute('CREATE TABLE ultimutt_ratings (id INT PRIMARY KEY AUTO_INCREMENT,Breed varchar(255),`All Around Friendliness` INT,`Trainability` INT,`Amount Of Shedding` INT,`Exercise Needs` INT,`General Health` varchar(255));')
# create 'size' table
engine.execute('CREATE TABLE ultimutt_size (id INT PRIMARY KEY AUTO_INCREMENT,Breed TEXT,`Average Height` INT,`Average Weight` INT);')
# create 'classification' table
engine.execute('CREATE TABLE ultimutt_class (id INT PRIMARY KEY AUTO_INCREMENT,Breed varchar(255),Classification varchar(255));')

In [172]:
# import ratings dataframe into db table
dfDogRatingsClean.to_sql('ultimutt_ratings', con=engine, if_exists='append', index = False)